"""MLAF Training Pipeline — Export Trained Weights to JavaScript.

Exports trained model artifacts into JS-compatible JSON:
  1. Gesture classifier weights → models/gesture_classifier_v1.json
  2. UASAM emission matrix → printable JS const
  3. Gaze emission matrix → printable JS const
  4. Fusion weights → printable JS const

Usage:
    python -m training.export_to_js
    python training/export_to_js.py
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import joblib
import numpy as np

from .config import (
    GAZE_STATES,
    GESTURE_IDS,
    GESTURE_LABEL_MAP,
    ID_TO_IDX,
    IDX_TO_ID,
    MODELS_DIR,
    NUM_GESTURE_CLASSES,
    UASAM_STATES,
)

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


# ---------------------------------------------------------------------------
# 1. Gesture classifier → JSON (for JS inference)
# ---------------------------------------------------------------------------

def export_gesture_classifier() -> Path | None:
    """Export Random Forest classifier as JS-compatible JSON.

    Exports the ensemble as a simplified lookup — for each tree, stores
    the feature index, threshold, and leaf values. This enables pure-JS
    inference without scikit-learn.
    """
    logger.info("=== Exporting Gesture Classifier ===")

    rf_paths = sorted(MODELS_DIR.glob("gesture_rf_*.joblib"))
    if not rf_paths:
        logger.warning("No RF model found — skipping classifier export")
        return None

    model = joblib.load(rf_paths[-1])
    logger.info("Loaded: %s", rf_paths[-1].name)

    # Extract decision tree structure for JS
    trees_json = []
    for i, tree in enumerate(model.estimators_):
        t = tree.tree_
        tree_data = {
            "feature": t.feature.tolist(),
            "threshold": [float(x) for x in t.threshold],
            "children_left": t.children_left.tolist(),
            "children_right": t.children_right.tolist(),
            "value": [
                [float(x) for x in row[0]]
                for row in t.value
            ],
        }
        trees_json.append(tree_data)

    export_data = {
        "_meta": {
            "model": "RandomForest",
            "source": str(rf_paths[-1]),
            "num_trees": len(trees_json),
            "num_classes": NUM_GESTURE_CLASSES,
            "gesture_ids": GESTURE_IDS,
            "gesture_labels": GESTURE_LABEL_MAP,
            "id_to_idx": ID_TO_IDX,
            "idx_to_id": {str(k): v for k, v in IDX_TO_ID.items()},
        },
        "trees": trees_json,
    }

    path = MODELS_DIR / "gesture_classifier_v1.json"
    with open(path, "w") as f:
        json.dump(export_data, f)
    size_mb = path.stat().st_size / (1024 * 1024)
    logger.info("  Saved: %s (%.2f MB, %d trees)", path, size_mb, len(trees_json))
    return path


# ---------------------------------------------------------------------------
# 2. UASAM emission matrix → JS const
# ---------------------------------------------------------------------------

def export_uasam_matrix() -> str | None:
    """Export UASAM emission matrix as a JavaScript const declaration."""
    logger.info("=== Exporting UASAM Emission Matrix ===")

    emission_path = MODELS_DIR / "emission_matrices.json"
    if not emission_path.exists():
        logger.warning("No emission matrices found — skipping UASAM export")
        return None

    with open(emission_path) as f:
        data = json.load(f)

    uasam = data.get("uasam_emission")
    if not uasam:
        logger.warning("No UASAM data in emission_matrices.json")
        return None

    # Generate JS
    lines = [
        "/**",
        " * UASAM Emission Matrix — P(vocalization_state | gesture)",
        " * Generated by MLAF training pipeline",
        f" * States: {UASAM_STATES}",
        " */",
        "export const UASAM_EMISSION = {",
    ]

    for gid in GESTURE_IDS:
        probs = uasam.get(gid, {})
        prob_str = ", ".join(f"'{s}': {probs.get(s, 0):.4f}" for s in UASAM_STATES)
        lines.append(f"  '{gid}': {{ {prob_str} }},")

    lines.append("};")

    js_code = "\n".join(lines)

    path = MODELS_DIR / "uasam_emission.js"
    with open(path, "w") as f:
        f.write(js_code)
    logger.info("  Saved: %s", path)
    return js_code


# ---------------------------------------------------------------------------
# 3. Gaze emission matrix → JS const
# ---------------------------------------------------------------------------

def export_gaze_matrix() -> str | None:
    """Export gaze emission matrix as a JavaScript const declaration."""
    logger.info("=== Exporting Gaze Emission Matrix ===")

    emission_path = MODELS_DIR / "emission_matrices.json"
    if not emission_path.exists():
        return None

    with open(emission_path) as f:
        data = json.load(f)

    gaze = data.get("gaze_emission")
    if not gaze:
        return None

    lines = [
        "/**",
        " * Eye Gaze Emission Matrix — P(gaze_state | gesture)",
        " * Generated by MLAF training pipeline",
        f" * States: {GAZE_STATES}",
        " */",
        "export const GAZE_EMISSION = {",
    ]

    for gid in GESTURE_IDS:
        probs = gaze.get(gid, {})
        prob_str = ", ".join(f"'{s}': {probs.get(s, 0):.4f}" for s in GAZE_STATES)
        lines.append(f"  '{gid}': {{ {prob_str} }},")

    lines.append("};")

    js_code = "\n".join(lines)

    path = MODELS_DIR / "gaze_emission.js"
    with open(path, "w") as f:
        f.write(js_code)
    logger.info("  Saved: %s", path)
    return js_code


# ---------------------------------------------------------------------------
# 4. Fusion weights → JS const
# ---------------------------------------------------------------------------

def export_fusion_weights() -> str | None:
    """Export fusion weights as a JavaScript const declaration."""
    logger.info("=== Exporting Fusion Weights ===")

    emission_path = MODELS_DIR / "emission_matrices.json"
    if not emission_path.exists():
        return None

    with open(emission_path) as f:
        data = json.load(f)

    fw = data.get("fusion_weights", {}).get("best_weights")
    if not fw:
        return None

    lines = [
        "/**",
        " * Multimodal Fusion Weights — optimized via grid search",
        " * Generated by MLAF training pipeline",
        " */",
        "export const FUSION_WEIGHTS = {",
        f"  visual: {fw.get('w_visual', 0.6):.4f},",
        f"  acoustic: {fw.get('w_acoustic', 0.2):.4f},",
        f"  gaze: {fw.get('w_gaze', 0.2):.4f},",
        "};",
    ]

    js_code = "\n".join(lines)

    path = MODELS_DIR / "fusion_weights.js"
    with open(path, "w") as f:
        f.write(js_code)
    logger.info("  Saved: %s", path)
    return js_code


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> dict:
    """Export all trained artifacts to JS-compatible format."""
    logger.info("MLAF Training Pipeline — Export to JavaScript")

    results: dict[str, str | None] = {}

    classifier_path = export_gesture_classifier()
    results["gesture_classifier"] = str(classifier_path) if classifier_path else None

    uasam_js = export_uasam_matrix()
    results["uasam_emission"] = "exported" if uasam_js else None

    gaze_js = export_gaze_matrix()
    results["gaze_emission"] = "exported" if gaze_js else None

    fusion_js = export_fusion_weights()
    results["fusion_weights"] = "exported" if fusion_js else None

    exported = sum(1 for v in results.values() if v is not None)
    logger.info("Export complete: %d / %d artifacts", exported, len(results))

    # Print summary for copy-paste into frontend
    print("\n" + "=" * 60)
    print("  JS Export Summary")
    print("=" * 60)
    for key, val in results.items():
        status = "OK" if val else "SKIPPED"
        print(f"  {key:<25} {status}")
    print("=" * 60)

    if classifier_path:
        size = classifier_path.stat().st_size / (1024 * 1024)
        print(f"\n  Classifier: {classifier_path} ({size:.2f} MB)")
    print(f"  Emission matrices: {MODELS_DIR / 'uasam_emission.js'}")
    print(f"  Gaze matrices: {MODELS_DIR / 'gaze_emission.js'}")
    print(f"  Fusion weights: {MODELS_DIR / 'fusion_weights.js'}")

    return results


if __name__ == "__main__":
    main()
    sys.exit(0)
