/**
 * Eye Gaze Emission Matrix — P(gaze_state | gesture)
 * Generated by MLAF training pipeline
 * States: ['direct', 'averted', 'tracking_hand', 'tracking_face']
 */
export const GAZE_EMISSION = {
  'subject_i': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'subject_you': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'subject_he': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'subject_she': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'subject_we': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'subject_they': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_want': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_eat': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_see': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_grab': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_drink': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_go': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'verb_stop': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'object_food': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'object_water': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'object_book': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'object_apple': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'object_ball': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
  'object_house': { 'direct': 0.2500, 'averted': 0.2500, 'tracking_hand': 0.2500, 'tracking_face': 0.2500 },
};