/**
 * UASAM Emission Matrix — P(vocalization_state | gesture)
 * Generated by MLAF training pipeline
 * States: ['silent', 'vocalization', 'speech_attempt', 'clear_speech']
 */
export const UASAM_EMISSION = {
  'subject_i': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'subject_you': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'subject_he': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'subject_she': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'subject_we': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'subject_they': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_want': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_eat': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_see': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_grab': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_drink': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_go': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'verb_stop': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'object_food': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'object_water': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'object_book': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'object_apple': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'object_ball': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
  'object_house': { 'silent': 0.2500, 'vocalization': 0.2500, 'speech_attempt': 0.2500, 'clear_speech': 0.2500 },
};